#! /bin/sh

set -eu

main() {
    context="$1"
    image=ivanbrennan/$(basename "$(realpath "$context")")
    version=$(cat "$context/VERSION")

    docker push "$image:$version" &&
        docker push "$image:latest"
}

dir=$(dirname "$0")
. "$dir/common"
run_main_with_args "$@"
